language: "es"
questionnaire_language: "es"
backend: "original"
title: "SALVA INTERNET EN EUROPA"
action: "¡Únete a nosotros y actúa! Envía un mensaje a tu regulador"
keywords:
  - net neutrality
  - connected conntinent
  - digital single market
  - dsm
  - BEREC
  - servicios específicos
  - gestión del tráfico
  - zero rating
