language: bg
title: За мрежова неутралност в Европа
action: Включи се и пиши на националния си регулатор!
keywords:
  - мрежова неутралност
  - свързан континент
  - цифров единен пазар
  - dsm
  - Нели Крус
  - net neutrality
  - Комисия за регулиране на съобщенията
  - специализирани услуги
  - истински интернет
  - BEREC
  - неутрални платформи
  - КРС
