language: "pt"
questionnaire_language: "en"
title: SALVA A INTERNET NA EUROPA
action: Junta-te a nós e actua! Envia uma mensagem ao regulador
keywords:
  - net neutrality
  - connected conntinent
  - digital single market
  - dsm
  - neelie kroes
  - Netzneutralität
  - drosselkom
  - specialised services
  - echtesnetz
  - BEREC
  - serviços específicos
  - gestão de tráfego
  - zero rating
