language: "pt"
questionnaire_language: "en"
title: SALVA A INTERNET NA EUROPA
action: Junta-te a nós e actua! Envia uma mensagem ao regulador
keywords:
  - neutralidade da Internet
  - Internet aberta
  - serviços específicos
  - gestão de tráfego
  - vias rápidas pagas
  - "taxa zero"
  - zero rating
  - Europa
  - Mercado único de telecomunicações
  - neutralidade da Internet
  - net neutrality
  - connected conntinent
  - digital single market
  - dsm
  - neelie kroes
  - drosselkom
  - specialised services
  - BEREC
  - Günther Oettinger
  - Internet
  - Open internet
  - Specialized services
  - Traffic management
  - BEREC
  - vias rápidas pagas
  - "taxa zero"
  - Europa
  - EU
  - Mercado único de telecomunicações
  - Autoridade Nacional de Comunicações, ANACOM
  - National Authority for Management and Regulation in Communications, ANCOM
  - European Commission, EC
  - PORTUGAL
