language: "en"
questionnaire_language: "en"
title: SAVE THE INTERNET IN EUROPE
action: Join us and take action! Send a message to your regulator
keywords:
  - net neutrality
  - connected conntinent
  - digital single market
  - dsm
  - neelie kroes
  - Netzneutralit채t
  - drosselkom
  - specialised services
  - echtesnetz
  - BEREC
  - Internetneutralit채t
  - Plattformneutralit채t
  - Neutralit채tsdebatte
