language: "pt"
language_name: "português"
questionnaire_language: "pt"
backend: "original"
title: "SALVA A INTERNET NA EUROPA"
action: "Junta-te a nós e actua! Envia uma mensagem ao regulador"
keywords:
  - neutralidade da Internet
  - Internet aberta
  - serviços específicos
  - gestão de tráfego
  - vias rápidas pagas
  - "taxa zero"
  - zero rating
  - Mercado único de telecomunicações
  - net neutrality
  - connected conntinent
  - digital single market
  - dsm
  - neelie kroes
  - drosselkom
  - specialised services
  - BEREC
  - Günther Oettinger
  - Internet
  - Open internet
  - Traffic management
  - Europa
  - EU
  - Autoridade Nacional de Comunicações, ANACOM
  - National Authority for Management and Regulation in Communications, ANCOM
  - European Commission, EC
  - PORTUGAL
