title:      "SAVE THE INTERNET IN EUROPE"
baseurl:    "https://savetheinternet.eu"
contentdir: "content/cr"
publishdir: "public/cr"
theme:      "sti"
layoutdir:  "layouts/cr"

params:
  language:   "cr"
  takeaction: "Join us and take action! Send a message to your regulator:"
