title:      "SAVE THE INTERNET IN EUROPE"
baseurl:    "https://savetheinternet.eu"
contentdir: "content/es"
publishdir: "public/es"
theme:      "sti"
layoutdir:  "layouts/es"

params:
  language:   "es"
  takeaction: "Join us and take action! Send a message to your regulator:"
