title:      "SAVE THE INTERNET IN EUROPE"
baseurl:    "https://savetheinternet.eu"
contentdir: "content/mt"
publishdir: "public/mt"
theme:      "sti"
layoutdir:  "layouts/mt"

params:
  language:   "mt"
  takeaction: "Join us and take action! Send a message to your regulator:"
