title:      "SAVE THE INTERNET IN EUROPE"
baseurl:    "https://savetheinternet.eu"
contentdir: "content/sv"
publishdir: "public/sv"
theme:      "sti"
layoutdir:  "layouts/sv"

params:
  language:   "sv"
  takeaction: "Join us and take action! Send a message to your regulator:"
