title:      "SAVE THE INTERNET IN EUROPE"
baseurl:    "https://savetheinternet.eu"
contentdir: "content/ro"
publishdir: "public/ro"
theme:      "sti"
layoutdir:  "layouts/ro"

params:
  language:   "ro"
  takeaction: "Join us and take action! Send a message to your regulator:"
