title:      "SAVE THE INTERNET IN EUROPE"
baseurl:    "https://savetheinternet.eu"
contentdir: "content/fi"
publishdir: "public/fi"
theme:      "sti"
layoutdir:  "layouts/fi"

params:
  language:   "fi"
  takeaction: "Join us and take action! Send a message to your regulator:"
