title:      "SAVE THE INTERNET IN EUROPE"
baseurl:    "https://savetheinternet.eu"
contentdir: "content/fr"
publishdir: "public/fr"
theme:      "sti"
layoutdir:  "layouts/fr"

params:
  language:   "fr"
  takeaction: "Join us and take action! Send a message to your regulator:"
