title:      "SAVE THE INTERNET IN EUROPE"
baseurl:    "https://savetheinternet.eu"
contentdir: "content/de"
publishdir: "public/de"
theme:      "sti"
layoutdir:  "layouts/de"

params:
  language:   "de"
  takeaction: "Mach mit und tu etwas! Sende eine Nachricht an die Regulierer:"
