title:      "SAVE THE INTERNET IN EUROPE"
baseurl:    "https://savetheinternet.eu"
contentdir: "content/hu"
publishdir: "public/hu"
theme:      "sti"
layoutdir:  "layouts/hu"

params:
  language:   "hu"
  takeaction: "Join us and take action! Send a message to your regulator:"
