title:      "SAVE THE INTERNET IN EUROPE"
baseurl:    "https://savetheinternet.eu"
contentdir: "content/de"
publishdir: "public/de"
layoutdir:  "layouts/de"
theme:      "sti"

params:
  language:    "de"
  description: "Sende eine Nachricht an die Regulierer!"
