baseurl:    "https://savetheinternet.eu/"
title:      "SAVE THE INTERNET"
contentdir: "content/en"
publishdir: "public/en"
theme:      "sti"

params:
  locale: "en-UK"
  home:
    tagline: "Join us and take action! Send a message to your regulator:"
    counter:
      message_description:   "people have sent a message"
      days_left_description: "days left"
    info:
      berec_decision_1:
        headline: "In 2015, the European Union adopted legislation on net neutrality..."
        body: <a href="http://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32015R2120">The EU Regulation</a> contains good principles to ensure that you can connect to any other point on the net without discrimination. However, some parts of the regulation could be abused to undermine net neutrality. The legislators decided to leave the responsibility for claryifing the uncertainties of the text to the telecoms regulators.
      berec_decision_2:
        headline: "The Body of European Regulators of Electronic Communications (BEREC) has to prepare implementation guidelines to interpret the ambiguities of the law by the end of August 2016. These guidelines will determine whether Europe will enjoy net neutrality or not."
      berec_decision_3:
        paragraph_1 : "In June 2016, BEREC plans to publish its draft guidelines and launch a public consultation. However, BEREC's procedural rules say that the public only has twenty working days to respond and the Regulation says that BEREC needs to publish its final guidelines on 30 August 2016. That means that citizens will only have one month to respond to the consultation and BEREC will only have a few weeks to process the (potentially thousands of) comments, draft updates to its guidelines and then go through the administrative processes to formally agree to any changes that it makes to the draft."
      net_neutrality_roadmap:
        headline: "EU Net Neutrality Roadmap"
      berec_decision_5:
        headline:    "This is a crucial moment: This is the step where big successes were achieved in the United States and India. Therefore, we have to continue pushing for real net neutrality by convincing the regulators about the value of a free and open Internet."
        paragraph_1: "Regulators need to equip themselves with the tools to enforce net neutrality. In Save The Internet, we think BEREC will not have enough time to process and duly take into account potentially tens of thousands of responses (the US telecoms regulator received 3.7 million responses to its consultation!). We can redress the balance by enabling everybody to properly contribute to the guidelines in a more efficient way."
        paragraph_2: "Recently, BEREC organised face-to-face meetings with stakeholder groups. We have translated the questions that BEREC asked stakeholders (<a href="https://edri.org/edris-first-input-on-net-neutrality-guidelines/">see here</a> and <a href="https://www.accessnow.org/rekindling-net-neutrality-our-meeting-with-eus-telecoms-regulators/">here</a>) in those meetings into plain English and added few others when we felt this was necessary."
        body: In June 2016, BEREC plans to publish its draft guidelines and launch a public consultation. However, BEREC's procedural rules say that the public only has twenty working days to respond and the Regulation says that BEREC needs to publish its final guidelines on 30 August 2016. That means that citizens will only have one month to respond to the consultation and BEREC will only have a few weeks to process the (potentially thousands of) comments, draft updates to its guidelines and then go through the administrative processes to formally agree to any changes that it makes to the draft.
      roadmap:
        title:  "EU Net Neutrality Roadmap"
      headline: "This is a crucial moment: This is the step where big successes were achieved in the United States and India. Therefore, we have to continue pushing for real net neutrality by convincing the regulators about the value of a free and open Internet."
      body01: "Regulators need to equip themselves with the tools to enforce net neutrality. In Save The Internet, we think BEREC will not have enough time to process and duly take into account potentially tens of thousands of responses (the US telecoms regulator received 3.7 million responses to its consultation!). We can redress the balance by enabling everybody to properly contribute to the guidelines in a more efficient way."
            body02: "Recently, BEREC organised face-to-face meetings with stakeholder groups. We have translated the questions that BEREC asked stakeholders (<a href="https://edri.org/edris-first-input-on-net-neutrality-guidelines/">see here</a> and <a href="https://www.accessnow.org/rekindling-net-neutrality-our-meeting-with-eus-telecoms-regulators/">here</a>) in those meetings into plain English and added few others when we felt this was necessary."
      cta: "BEREC <a href="#send-a-message">needs your input</a> before they decide on the future of net neutrality in Europe."
      fixnetneutrality:
        title: "What needs to be fixed"
        fix01:
          headline: "Specialized Services"
      body:     "Specialised Services risk becoming the paid fast-lane for big Internet companies that push every other website, idea and start-up into the slowlane."
      readmore: "read more in FAQ"
      fix02:
        headline: "Traffic Management"
      body:     "Don't let your Internet provider decide what traffic is important and which online services it slows down, at its own discretion."
      readmore: "read more in FAQ"
      fix03:
        headline: "Zero Rating"
        body:     "It sounds like you get something for free, but it makes your mobile operator become a gatekeeper and gives it a reason for lower monthly data caps."
        readmore: "read more in FAQ"
    questions:
      headline: "Tell your national regulators and BEREC to protect net neutrality"
      body:     "Tell your regulators your opinion on the new net neutrality rules by using the questionnaire tool below. By answering the multiple choice and open questions an email will be generated for you. Your email will be submitted by us to the EU Telecom Regulators (BEREC) when the official consultation starts in June 2016."
    spreadtheword:
      title: "Spread the word!"
    stayinformed:
      title: "Stay informed!"
      mail:  "Your Email:"
      country: "Choose country:"
    sponsors:
      abstract: "We are concerned citizens from NGOs around Europe that care about civil liberties in the digital realm."
      support:  "With friendly support from"
