title:      "SAVE THE INTERNET IN EUROPE"
baseurl:    "https://savetheinternet.eu"
contentdir: "content/hr"
publishdir: "public/hr"
theme:      "sti"
layoutdir:  "layouts/hr"

params:
  language:   "hr"
  takeaction: "Join us and take action! Send a message to your regulator:"
