baseurl:    "https://savetheinternet.eu"
contentdir: "content/en"
publishdir: "public/en"
title:      "SAVE THE INTERNET IN EUROPE"
theme:      "sti"

params:
  language:    "en"
  description: "Send a message to your regulator!"
