title:      "SAVE THE INTERNET IN EUROPE"
baseurl:    "https://savetheinternet.eu"
contentdir: "content/en"
publishdir: "public/en"
theme:      "sti"

params:
  language:   "en"
  takeaction: "Join us and take action! Send a message to your regulator:"
