title:      "SAVE THE INTERNET IN EUROPE"
baseurl:    "https://savetheinternet.eu"
contentdir: "content/ga"
publishdir: "public/ga"
theme:      "sti"
layoutdir:  "layouts/ga"

params:
  language:   "ga"
  takeaction: "Join us and take action! Send a message to your regulator:"
