title:      "SAVE THE INTERNET IN EUROPE"
baseurl:    "https://savetheinternet.eu"
contentdir: "content/da"
publishdir: "public/da"
theme:      "sti"
layoutdir:  "layouts/da"

params:
  language:   "da"
  takeaction: "Join us and take action! Send a message to your regulator:"
