title:      "SAVE THE INTERNET IN EUROPE"
baseurl:    "https://savetheinternet.eu"
contentdir: "content/et"
publishdir: "public/et"
theme:      "sti"
layoutdir:  "layouts/et"

params:
  language:   "et"
  takeaction: "Join us and take action! Send a message to your regulator:"
