baseurl:    "https://savetheinternet.eu"
title:      "SAVE THE INTERNET"
contentdir: "content/de"
publishdir: "public/de"
<<<<<<< HEAD
layoutdir:  "layouts/de"
=======
>>>>>>> katrinleinweber-translate-de-some-more
theme:      "sti"

params:
  language: "de"
