baseurl: "https://savetheinternet.eu"
contentdir: "content/en"
publishdir: "public/en"
title: "Save the Internet in Europe"
theme: "sti"

params:
  language: "en"
  Description: "Contact your representative today!"
