title:      "SAVE THE INTERNET IN EUROPE"
baseurl:    "https://savetheinternet.eu"
contentdir: "content/sl"
publishdir: "public/sl"
theme:      "sti"
layoutdir:  "layouts/sl"

params:
  language:   "sl"
  takeaction: "Join us and take action! Send a message to your regulator:"
