title:      "SAVE THE INTERNET IN EUROPE"
baseurl:    "https://savetheinternet.eu"
contentdir: "content/it"
publishdir: "public/it"
theme:      "sti"
layoutdir:  "layouts/it"

params:
  language:   "it"
  takeaction: "Join us and take action! Send a message to your regulator:"
