title:      "SAVE THE INTERNET IN EUROPE"
baseurl:    "https://savetheinternet.eu"
contentdir: "content/lt"
publishdir: "public/lt"
theme:      "sti"
layoutdir:  "layouts/lt"

params:
  language:   "lt"
  takeaction: "Join us and take action! Send a message to your regulator:"
