title:      "SAVE THE INTERNET IN EUROPE"
baseurl:    "https://savetheinternet.eu"
contentdir: "content/pl"
publishdir: "public/pl"
theme:      "sti"
layoutdir:  "layouts/pl"

params:
  language:   "pl"
  takeaction: "Join us and take action! Send a message to your regulator:"
