language: "se"
questionnaire_language: "en"
title: RÄDDA INTERNET I EUROPA
action: Agera nu! Skicka ett meddelande till regleringsmyndigheten i ditt land
keywords:
  - nätneutralitet
  - öppet internet
  - specialiserade tjänster
  - trafikhantering
  - betalda gräddfiler
  - nollmätning
  - Europa
  - inre marknad för telekommunikation
  - nätverksneutralitet
