language: "pl"
questionnaire_language: "pl"
title: SAVE THE INTERNET W EUROPIE
action: Dołącz do nas i działaj! Prześlij wiadomość do swojego urzędu regulacyjnego
keywords:
  - neutralność sieci
  - otwarty Internet
  - wyspecjalizowane usługi
  - zarządzanie ruchem
  - płatne szybkie pasy
  - zero-rating
  - Europa
  - Jednolity rynek telekomunikacyjny
  - neutralność sieci
