language: "et"
questionnaire_language: "et"
backend: "original"
title: PÄÄSTA EUROOPA INTERNET
action: Liituge ja asuge tegutsema! Saatke sõnum oma reguleerivale asutusele
keywords:
  - võrguneutraalsus
  - avatud Internet
  - eriteenused
  - liikluskorraldus
  - makstud kiirliinid
  - nullmäär
  - Euroopa
  - elektroonilise side ühtne turg
  - võrguneutraalsus
