language: "da"
questionnaire_language: "da"
title: RED INTERNETTET I EUROPA
action: Vær med og gør noget! Skriv til tilsynsmyndighederne
keywords:
  - netneutralitet
  - åbent internet
  - specialtjenester 
  - trafikstyring
  - betalingskrævende hurtigbaner
  - nultaksering
  - Europa
  - indre marked for teletjenester
  - netværksneutralitet
  - net neutrality
  - network neutrality
  - Günther Oettinger
