language: "ro"
questionnaire_language: "ro"
title: SALVEAZĂ INTERNETUL ÎN EUROPA
action: Vino alături de noi și treci la acțiune! Trimite un mesaj autorității de reglementare în telecomunicații din țara ta
keywords:
  - neutralitatea Internetului
  - continent conectat
  - piața digitală unică
  - dsm
  - neelie kroes
  - servicii specializate
  - BEREC
