language: "hu"
questionnaire_language: "hu"
title: SAVE THE INTERNET IN EUROPE
action: Csatlakozzon hozzánk és cselekedjen! Küldjön üzenetet az Ön országában működő szabályozó hatóságnak
keywords:
  - hálózati semlegesség
  - nyílt internet
  - specializált szolgáltatások
  - forgalomszabályozás
  - fizetett gyorssávok
  - zero rating
  - Európa
  - Távközlés egységes piac
  - hálózatsemlegesség
