language: "fi"
questionnaire_language: "fi"
backend: "original"
title: PELASTA INTERNET EUROOPASSA
action: Osallistu t채h채n kampanjaan ja tee jotakin! L채het채 viesti valvojalle:
keywords:
  - Verkkoneutraliteetti
  - Erikoispalvelut
  - Internet-neutraliteetti
  - Platform-neutraliteetti
  - Neutraliteettikeskustelu
  - net neutrality
  - network neutrality
