language: "lv"
questionnaire_language: "en"
backend: "original"
title: "GLĀB INTERNETU EIROPĀ"
action: "Piedalies un dari kaut ko! Nosūti ziņu regulatoriem"
keywords:
  - tīkla neitralitāte
  - speciālie pakalpojumi
  - interneta neitralitāte
  - platformu neitralitāte
  - debates par neitralitāti
