language: "sl"
questionnaire_language: "en"
title: REŠITE INTERNET V EVROPI
action: Pridružite se nam in ukrepajte! Pošljite sporočilo vašemu regulatorju
keywords:
 - internetna nevtralnost
 - odprti internet
 - specializirane storitve
 - upravljanje prometa
 - plačane hitre linije
 - zero-rating
 - Evropa
 - Telecom Single Market
 - nevtralnost omrežja
 - net neutrality
 - network neutrality
 - Günther Oettinger
 - Internet
 - Open internet
 - Specialized services
 - Traffic management
 - BEREC
 - paid fast lanes
 - Europe
 - EU
 - Telecom Single Market
 - Slovenia
 - Post and Electronic Communications Agency, APEK
 - Post and Electronic Communications Agency of the Republic of Slovenia
