language: "el"
questionnaire_language: "el"
backend: "original"
title: "ΣΩΣΤΕ ΤΟ ΔΙΑΔΙΚΤΥΟ ΣΤΗΝ ΕΥΡΩΠΗ"
action: "Ακολουθήστε μας και αναλάβετε δράση! Στείλτε ένα μήνυμα στη Ρυθμιστική σας Αρχή"
keywords:
  - ουδετερότητα των δικτύων
  - ανοικτό διαδίκτυο
  - εξειδικευμένες υπηρεσίες
  - διαχείριση κίνησης
  - γρήγορες λωρίδες επί πληρωμή
  - zero-rating
  - Ευρώπη
  - Ενιαία Τηλεπικοινωνιακή Αγορά
  - ουδετερότητα δικτύων
