language: "de"
questionnaire_language: "de"
title: "RETTE DAS INTERNET IN EUROPA"
action: "Mach mit und tu etwas! Sende eine Nachricht an die Regulierer:"
keywords:
  - net neutrality
  - connected continent
  - digital single market
  - dsm
  - neelie kroes
  - Netzneutralit채t
  - drosselkom
  - specialised services
  - echtesnetz
  - BEREC
  - Internetneutralit채t
  - Plattformneutralit채t
  - Neutralit채tsdebatte
