language: "sk"
questionnaire_language: "sk"
backend: "original"
title: ZACHRÁŇME INTERNET V EURÓPE
action: Pridajte sa k nám a zakročte! Pošlite Vášmu regulátorovi správu
keywords:
  - neutralita siete
  - otvorený internet
  - špecializované služby
  - riadenie prevádzky
  - platené rýchle pruhy
  - nulová sadzba
  - Európa
  - jednotný trh pre telekomunikačné služby
  - neutralita siete
